#Список возможных API
apis: weatherapi,openweathermap
#Настройка с какого API  получать данные, если использовать all данные в списке будут из всех источников
defaultApi: openweathermap
#Порт приложения
server:
    port: 7777
#Название приложения    
spring:
    application:
        name: WeatherForecastService
#Город по умолчанию       
town: Moscow
# Настройка API openweathermap
openweathermap:
    params:
        city:
            name: q
        days:
            name: cnt
            value: 9
        key:
            name: appid
            value: 928ebd8d3e967da51398fce48a97561c
    requestUrl: http://api.openweathermap.org/data/2.5/forecast?
# Настройка API weatherapi
weatherapi:
    params:
        city:
            name: q
        days:
            name: days
            value: 1
        key:
            name: key
            value: c75543c70d5c486aa6c164531240604
    requestUrl: https://api.weatherapi.com/v1/forecast.json?
